version: '3'
services:
  app:
    build: .
    tty: true 
    stdin_open: true
    working_dir: /app
    env_file: 
      - api.env
    volumes:
      - .:/app
    ports:
      - "${HOST_PORT:-8080}:${CONTAINER_PORT:-8080}"
    command: bash -c "go run main.go" #立ち上げたのに、コンテナ入ってbuildするのだるい
    depends_on:
      - "db"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${DATABASE:-test}"
      MYSQL_USER: "${USER:-go_app_user}"
      MYSQL_PASSWORD: "${USER_PASSWORD:-go_test}"
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - go-db-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  go-db-data:
    